export const newReleases = [
  {
    id: 1,
    title: "Firestarter",
    image: "firestarter.jpg",
    rating: "4.5",
    description: "A young girl tries to understand how she mysteriously gained the power to set things on fire with her mind.",
    year: 2022,
    genre: "Sci-Fi",
    duration: "1h 34m",
  },
  {
    id: 2,
    title: "Pushpa",
    image: "pushpa.jpg",
    rating: "4.7",
    description: "A laborer rises through the ranks of a red sandalwood smuggling syndicate, making many enemies in the process.",
    year: 2021,
    genre: "Action",
    duration: "2h 59m",
  },
  {
    id: 3,
    title: "Blade Runner",
    image: "bladerunner.jpg",
    rating: "4.8",
    description: "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth.",
    year: 1982,
    genre: "Sci-Fi",
    duration: "1h 57m",
  },
  {
    id: 4,
    title: "Kahaani",
    image: "kahaani.jpg",
    rating: "4.6",
    description: "A pregnant woman travels to Kolkata in search of her missing husband, but everyone insists he never existed.",
    year: 2012,
    genre: "Thriller",
    duration: "2h 2m",
  },
];

export const recommendations = [
  {
    id: 5,
    title: "The Grinch",
    image: "grinch.jpg",
    rating: "4.2",
    description: "A grumpy Grinch plots to ruin Christmas for the residents of his town.",
    year: 2018,
    genre: "Animation",
    duration: "1h 26m",
  },
  {
    id: 6,
    title: "Blade Runner",
    image: "bladerunner.jpg",
    rating: "4.8",
    description: "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth.",
    year: 1982,
    genre: "Sci-Fi",
    duration: "1h 57m",
  },
  {
    id: 7,
    title: "Spider-Man",
    image: "spiderman.jpg",
    rating: "4.9",
    description: "After being bitten by a genetically altered spider, a young man gains spider-like abilities and fights crime.",
    year: 2002,
    genre: "Action",
    duration: "2h 1m",
  },
];

export const popularMovies = [
  {
    id: 8,
    title: "Queen",
    image: "queen.jpg",
    rating: "4.8",
    description: "A young woman embarks on a solo honeymoon trip to Europe after her marriage falls apart.",
    year: 2013,
    genre: "Drama",
    duration: "2h 26m",
  },
  {
    id: 9,
    title: "The Jungle Book",
    image: "junglebook.jpg",
    rating: "4.5",
    description: "An orphan boy is raised in the jungle with the help of a pack of wolves, a bear, and a black panther.",
    year: 2016,
    genre: "Adventure",
    duration: "1h 46m",
  },
  {
    id: 10,
    title: "Blade Runner",
    image: "bladerunner.jpg",
    rating: "4.8",
    description: "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth.",
    year: 1982,
    genre: "Sci-Fi",
    duration: "1h 57m",
  },
];
